services:
  # Node.js Application
  app:
    build: .
    container_name: quiknotes-app
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    environment:
      NODE_ENV: production
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      RESET_DB: "false"
      PORT: 8080
    volumes:
      - ./dist:/app/dist
